<div data-role="content" class="ui-grid-b">
	<div id="block-a">
		<ul data-role="listview" data-inset="true">
			<li data-role="list-divider">Opciones</li>
			<li data-icon="add"><a href="<?=$this->baseUrl();?>/acceso/roles/add">Nuevo</a></li>
		</ul>
	</div>

	<div id="block-b" class="ui-block-b" data-theme="c">
		<ul data-role="listview" data-inset="true">
			<li data-role="list-divider">Roles</li>
			<li>

				<?php if(sizeof($this->resultados) > 0):?>
					<table>
						<thead>
							<tr class="ui-bar-d">
								<th width="180">(<?=sizeof($this->resultados);?>) Roles</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<?php foreach($this->resultados as $i => $v): ?>
								<tr class="ui-btn-up-c">
									<td><?=$v['rol_nombre'];?></td>
									<td><a data-icon="icon-menu" href="<?=$this->baseurl();?>/acceso/roles/edit/rol_id/<?=$v['rol_id'];?>" class="button green-gradient tiny">editar</a> <a href="<?=$this->baseurl();?>/acceso/roles/manage/rol_id/<?=$v['rol_id'];?>" data-icon="icon-gear" class="button tiny green-gradient">gestionar</a></td>
								</tr>
								<?php endforeach;?>
						</tbody>
					</table>
					<?php else: ?>
					<p>No hay Roles Cargados.</p>
					<?php endif;?>

			</li>
		</ul>
	</div>
</div>