<div data-role="content" class="ui-grid">
	<ul data-role="listview" data-inset="true" data-theme="e">
		<li data-role="list-divider">Activaciones Listado</li>
		<li>
			<form action="<?=$this->baseUrl();?>/activaciones" method="post" id="query_log">
				<table>
					<tr>
						<td><?=$this->form->campo->renderViewHelper();?></td>
						<td><?=$this->form->query->renderViewHelper();?></td>
						<td><label><?=$this->form->tilde->renderViewHelper();?> avanzado</label></td>
						<td><button data-icon="search" data-mini="true" data-inline="true" type="submit">Buscar</button></td>
					</tr>
				</table>
				<p style="margin-top:3px;vertical-align:top"><?=$this->form->texto->renderViewHelper();?>
					<?php if($this->error) :?>
						<b style="vertical-align:top"> &nbsp; &nbsp;Errores:</b>
					<?=$this->form->error->renderViewHelper();?></p>
					<?php endif; ?>
			</form>
			<?php
				if(is_null($this->activaciones)):
					elseif(sizeof($this->activaciones) > 0): ?>
				<form method="post" action="<?=$this->baseUrl();?>/activaciones/index/asignacion" id="form_asigna">
					<!--<button type="button" data-inline="true" data-mini="true" data-icon="forward" class="button" id="asigna_boton">Asignar a Vendedor</button>-->
					<div class="pad button-height"><?=sizeof($this->activaciones);?> Resultados encontrados.</div>
					<input type="hidden" name="ven_id" value="" id="ven_id" />
					<input type="hidden" name="suc_id" value="" id="sucursal" />
					<table id="results">
						<thead>
							<tr class="ui-bar-b" align="center">
								<td><input data-role="none" type="checkbox" onclick="$('.trow').attr('checked',$(this).is(':checked'))" /></td>
								<th>SIM</th>
								<th>Abonado</th>
								<th>Solicitud</th>
								<th>Estado Actual</th>
								<th>Lote SIM</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach($this->activaciones as $i => $v): ?>
								<tr class="<?=($v['activacion_estado'] != 'Finalizado') ? 'ui-btn-down-e' : 'ui-btn-up-c';?>">
									<td><input class="trow" data-role="none" type="checkbox" name="ids[]" value="<?=$v['activacion_sim'];?>" /></td>
									<td>&nbsp;<?=$v['activacion_sim'];?></td>
									<td><?=$v['activacion_linea'];?></td>
									<td><?=$v['activacion_nroSol'];?></td>
									<td><?=$v['activacion_estado'];?></td>
									<td><a target="_blank" href="<?=$this->baseUrl();?>/activaciones/index/ver-lote/lote/<?=$v['cod'];?>"><?=$v['cod'];?>XXX</a></td>
								</tr>
								<?php endforeach; ?>
						</tbody>
					</table>
				</form>

				<!-- Asigna a vendedor -->
				<div id="asigna_vend" style="display: none;width:600px;">
					<button type="button" class="button" onclick="$('#form_asigna,#asigna_vend,#query_log').slideToggle();">&laquo; Modificar</button><br /><br />
					<div class="pad button-height"><b id="asigna_rr"></b> Resultados seleccionados.</div>
					<fieldset class="fieldset">
						<legend class="legend">Seleccione Vendedor</legend>
						<div><?=$this->form_select->renderViewHelper();?>
							<select id="vendor" size="10" style="height: 100px;"></select>

							<input type="text" class="input" placeholder="Vendedor" id="search" /></div>
						<br />
						<center><button id="proceso" type="button" class="button">Asignar &raquo;</button></center>
					</fieldset>

					<script type="text/javascript">
						$.get('<?=$this->baseUrl();?>/json/vendedores',function(d){
							$vend = d;
							$('#suc_id').bind('change',function(){
								var s = '';
								$($vend[$(this).val()]).each(function(i,v){
									s += '<option value="'+v.idpunto+'">'+v.nombre+'</option>';
								});
								$('#vendor').html(s);
							}).show().trigger('change');
						},'json');
						$('#asigna_boton').live('click',function(){
							if($('#results .trow:checked').length > 0){
								$('#asigna_rr').html($('#results .trow:checked').length);
								return $('#form_asigna,#asigna_vend,#query_log').slideToggle();
							}
							alert('Debe seleccionar elementos');
						});
						$('#search').live('input keyup',function(){
							var s = $(this).val().toLowerCase().split(" ");
							if(s == '') return;
							$.each(s, function(i,v){
								$("#vendor option:not(:selected)").filter(function(e){
									return (new RegExp(v,'i').test($(this).text().toLowerCase()));
								}).eq(0).attr('selected',true);
							});
						});
						$('#proceso').click(function(){
							if($('#vendor').val() == null || $('#vendor').val() == ''){
								return alert('Seleccione Vendedor.');
							}
							$('#ven_id').val($('#vendor').val());
							$('#sucursal').val($('#suc_id').val());
							$('#form_asigna').submit();
						});
					</script>

				</div>

				<?php else: ?><div data-icon="alert">No se encontraron resultados relacionados</div>
				<?php endif; ?>

			<script type="text/javascript">
				$('#tilde').live('click',function(){
					$('#query').attr('disabled',$(this).is(':checked'));
					return ($(this).is(':checked')) ? $('#texto').show() : $('#texto').hide();
				});
			</script>
		</li>
	</ul>
</div>