<div data-role="content" class="ui-grid-b">
	<div id="block-a">

		<ul data-role="listview" data-inset="true" data-theme="e">
			<li data-role="list-divider">Buscar Usuario</li>
			<li><form action="<?=$this->baseUrl();?>/usuarios/index" method="post">
					<?=$this->fbuscar->q->renderViewHelper();?> <button data-inline="true" data-mini="true" title="Buscar" data-icon="search" data-iconpos="notext" type="submit"></button><br />
					<?php if($this->fbuscar->q->getValue() != ''): ?><a data-theme="e" data-role="button" data-icon="delete" data-inline="true" data-mini="true" href="<?=$this->baseUrl();?>/usuarios/index">Limpiar Busqueda</a><?php endif;?>
				</form></li>
			<li><b><?=$this->total;?></b> registros en total</li>
		</ul>
	</div>

	<div id="block-b" class="ui-block-b" data-theme="c">
		<ul data-role="listview" data-inset="true">
			<li data-role="list-divider">Usuarios</li>
<?php foreach($this->usuarios as $i => $v){ ?>
			<li data-icon="gear"><a href="<?=$this->baseUrl();?>/usuarios/permisos/index/usu_id/<?=$v['idusuario'];?>"><?=$v['Apellido'];?>, <?=$v['nombre'];?> [<?=$v['username'];?>]</a></li>
				<?php } ?>
<?php if($this->paginas > 1):?>
			<li><?=$this->paginador($this->paginas);?></li>
<?php endif;?>
		</ul>

	</div>
</div>