<div data-role="content" class="ui-grid-b">
	<div id="block-a">
		<form method="post" action="<?=$this->baseUrl();?>/logistica/index/equipos-sucursal">
			<ul data-role="listview" data-inset="true" data-theme="e">
				<li data-role="list-divider">Equipos Sucursal</li>
				<li><?=$this->form->suc_id->renderViewHelper();?></li>
				<li><?=$this->form->pun_id->renderViewHelper();?></li>
				<li><?=$this->form->mar_id->renderViewHelper();?></li>
				<li><?=$this->form->mod_id->renderViewHelper();?></li>
				<li><button data-theme="a" data-inline="true" data-mini="true" data-icon="search" title="Buscar" type="submit">Buscar</button>
				</li>
			</ul>
		</form>
		<?php if(sizeof($this->equipos) > 0): ?>
			<center>
				<a data-theme="e" data-role="button" data-inline="true" data-mini="true" data-icon="gear" href="javascript:;" class="imprimir">Imprimir</a> <a data-theme="e" data-role="button" data-mini="true" data-inline="true" data-icon="gear" href="javascript:;" class="exportar">Exportar</a>
			</center>
			<?php endif; ?>
	</div>

	<?php if(!is_null($this->equipos)): ?>
		<div id="block-b" class="ui-block-b" data-theme="c">
			<ul data-role="listview" data-inset="true">
				<li data-role="list-divider"><b><?=sizeof($this->equipos);?></b> Articulos encontrados</li>
				<li>
					<?php if(!empty($this->equipos)): ?>
						<table>
							<thead>
								<tr class="ui-bar-b" align="center">
									<?php if($this->suc_id == 0): ?><th width="140">Sucursal</th><?php endif; ?>
									<?php if($this->pun_id == 0): ?><th width="180">Punto de Venta / Vendedor</th><?php endif; ?>
									<th width="90">Marca</th>
									<th width="190">Modelo</th>
									<th>Cantidad</th>
									<th>Costo</th>
									<th>Costo Real</th>
								</tr>
							</thead>
							<tbody>
								<?php foreach($this->equipos as $i => $v): ?>
									<tr class="ui-btn-up-c">
										<?php if($this->suc_id == 0): ?><td><?=$this->cache_sucursales[$v['idsucursal']];?></td><?php endif; ?>
										<?php if($this->pun_id == 0): ?><td>
											<?=($v['idvendedor'] != '') ? $this->cache_vendedores[$v['idvendedor']] : $this->cache_puntos[$v['idpunto']];?>

										</td><?php endif; ?>
										<td><?=$v['marca'];?></td>
										<td><?=$v['modelo'];?></td>
										<td align="right"><?=$v['cant'];?></td>
										<td align="right"><?=$this->currency->toCurrency($v['costo']);?></td>
										<td align="right"><?=$this->currency->toCurrency($v['creal']);?></td>
									</tr>
									<?php endforeach; ?>
							</tbody>
						</table>
						<?php else: ?>
						<p>Los resultados no pueden ser visualizados. No existen Ingresos para la fecha requerida.</p>
						<?php endif; ?>
				</li>
			</ul>

		</div>
		<?php endif; ?>
</div>

<script type="text/javascript">
	$.get('<?=$this->baseUrl();?>/json/modelos',function(d){
		$modelos = d;
		$('#mar_id').bind('change',function(){
			var s = '<option value="">[Modelos]</option>';
			$($modelos[+$(this).val()]).each(function(i,v){
				s += '<option value="'+v.idmodelo+'">'+v.modelo+'</option>';
			});
			$('#mod_id').html(s).val('<?=$this->mod_id;?>');
		}).show().trigger('change');
	},'json');
	$.get('<?=$this->baseUrl();?>/json/puntos-venta',function(d){
		$puntos = d;
		$('#suc_id').bind('change',function(){
			var s = '<option value="">[Puntos de Venta]</option>';
			$($puntos[+$(this).val()]).each(function(i,v){
				s += '<option value="'+v.idpunto+'">'+v.nombre+'</option>';
			});
			$('#pun_id').html(s).val('<?=$this->pun_id;?>').change();
		}).show().change();
	},'json');

</script>