<div data-role="content" class="ui-grid" id="content">
	<ul data-role="listview" data-inset="true" data-theme="c">
		<li data-role="list-divider">Egresos por Punto - <b><?=$this->periodo;?></b></li>
		<li><p>Punto: <?=$this->cache_puntos[$this->pun_id];?></p>

			<?php if(is_null($this->resultados)){
				} elseif(sizeof($this->resultados) > 0) { ?>
				<table>
					<thead>
						<tr class="ui-bar-b" align="center">
							<th>Sucursal</th>
							<th>Vendedor</th>
							<th>Cantidad</th>
							<th>Total</th>
							<th>Operaci&oacute;n</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach($this->resultados as $i => $v){ ?>
							<tr class="ui-btn-up-c">
								<td><?=$this->cache_sucursales[$v['idsucursal']];?></td>
								<td><a data-legend="Detalle Vendedor/Punto" target="_blank"  href="<?=$this->baseUrl();?>/accesorios/egresos/vendedor/pun_id/<?=$v['idpunto'];?>/ven_id/<?=$v['idvendedor'];?>/ope/<?=$this->ope;?>/desde/<?=$this->desdeUrl;?>/hasta/<?=$this->hastaUrl;?>"><?=$this->cache_vendedores[$v['idvendedor']];?></a></td>
								<td align="right"><?=$v['cant'];?></td>
								<td align="right"><?=$this->currency->toCurrency($v['precio']);?></td>
								<td align="right"><?=$v['Operacion'];?></td>
							</tr>
							<?php $total1 += $v['cant'];
								$total2 += $v['precio'];
						} ?>
						<tr class="ui-bar-c">
							<td colspan="2"></td>
							<td align="right"><?=$total1;?></td>
							<td align="right"><?=$this->currency->toCurrency($total2);?></td>
							<td></td>
						</tr>
					</tbody>
				</table>
				<?php } else { ?>
				<p>No hay resultados relacionados.</p>
				<?php } ?>
		</li>
	</ul>
</div>

<a data-theme="e" data-role="button" data-inline="true" data-mini="true" data-icon="gear" href="javascript:;" class="imprimir">Imprimir</a> <a data-theme="e" data-role="button" data-mini="true" data-inline="true" data-icon="gear" href="javascript:;" class="exportar">Exportar</a>



<script type="text/javascript">
	$.get('<?=$this->baseUrl();?>/json/puntos-venta',function(d){
		$puntos = d;
		$('#suc_id').bind('change',function(){
			var s = '<option value="">[Todos]</option>';
			$($puntos[+$(this).val()]).each(function(i,v){
				s += '<option value="'+v.idpunto+'">'+v.nombre+'</option>';
			});
			$('#pun_id').html(s).val('<?=$this->pun_id;?>');
		}).show().trigger('change');
	},'json');

</script>
