<div data-role="content" class="ui-grid-b">
	<div id="block-a">
		<ul data-role="listview" data-inset="true" data-theme="e">
			<li data-role="list-divider">Buscar Usuario</li>
			<li><form action="<?=$this->baseUrl();?>/acceso/usuarios/index" method="post">
					<?=$this->fbuscar->q->renderViewHelper();?>	<?php if($this->fbuscar->q->getValue() != ''): ?><a data-role="button" data-inline="true" data-legend="Limpiar Busqueda" data-theme="e" data-icon="delete" data-iconpos="notext" data-mini="true" href="<?=$this->baseUrl();?>/acceso/usuarios"></a><?php endif;?>
					<button data-inline="true" data-mini="true" data-icon="search" type="submit">Buscar</button>
				</form></li>
		</ul>
	</div>

	<div id="block-b" class="ui-block-b" data-theme="c">
		<ul data-role="listview" data-inset="true">
			<li data-role="list-divider">Usuarios - <b><?=$this->total;?></b> registros en total</li>
			<?php foreach($this->usuarios as $i => $v){ ?>
				<li data-icon="gear"><a href="<?=$this->baseUrl();?>/acceso/usuarios/manage/usu_id/<?=$v['idusuario'];?>"><?=$v['Apellido'];?>, <?=$v['nombre'];?> [<?=$v['username'];?>]</a></li>
				<?php } ?>
			<?php if($this->paginas > 1):?>
				<li><?=$this->paginador($this->paginas);?></li>
				<?php endif;?>
		</ul>

	</div>
</div>