<div data-role="content" class="ui-grid-b">
	<div id="block-a">
		<ul data-role="listview" data-inset="true" data-theme="e">
			<li data-role="list-divider">Descargas</li>
			<li>por favor seleccione el archivo de la lista y guardelo en su pc.<br />el software se debe instalar posteriormente.</li>
		</ul>
	</div>

	<div id="block-b" class="ui-block-b" data-theme="c">
		<ul data-role="listview" data-inset="true">
			<li data-role="list-divider">Aplicaciones</li>
			<li>
				<table width=460 border=0>
					<tr>
						<td colspan=2 width=120>
							<p style="border-top: none; border-bottom: 1px solid #808080; border-left: none; border-right: none; padding-top: 0cm; padding-bottom: 0.05cm; padding-left: 0cm; padding-right: 0cm">
								archivo</p>
						</td>
						<td width=33>
							<p style="border-top: none; border-bottom: 1px solid #808080; border-left: none; border-right: none; padding-top: 0cm; padding-bottom: 0.05cm; padding-left: 0cm; padding-right: 0cm">
								os</p>
						</td>
						<td width=177>
							<p style="border-top: none; border-bottom: 1px solid #808080; border-left: none; border-right: none; padding-top: 0cm; padding-bottom: 0.05cm; padding-left: 0cm; padding-right: 0cm">
								descripcion</p>
						</td>
						<td width=60>
							<p style="border-top: none; border-bottom: 1px solid #808080; border-left: none; border-right: none; padding-top: 0cm; padding-bottom: 0.05cm; padding-left: 0cm; padding-right: 0cm">
								version</p>
						</td>
						<td width=39>
							<p style="border-top: none; border-bottom: 1px solid #808080; border-left: none; border-right: none; padding-top: 0cm; padding-bottom: 0.05cm; padding-left: 0cm; padding-right: 0cm">
								tama&ntilde;o</p>
						</td>
					</tr>
					<tr valign=top>
						<td width=30>
							<p><a href="http://190.210.182.194/web/public/archivos/cell-agent.rar"><img src="http://190.210.182.194/web/public/archivos/downloadfile.png" name="gr&aacute;ficos6" align=bottom width=27 height=21 border=0></a></p>
						</td>
						<td width=81>
							<p><a href="http://190.210.182.194/web/public/archivos/cell-agent.rar">cell-agent</a></p>
						</td>
						<td width=100>
							<p>all win</p>
						</td>
						<td width=177>
							<p>Actualizacion sistema ventas con modulo fiscal.</p>
						</td>
						<td width=100>
							<p><a href="http://190.210.182.194/web/public/cambios.htm">10.0.44 </a>
							</p>
						</td>
						<td width=100>
							<p align=center>2215 kb</p>
						</td>
					</tr>
					<tr valign=top>
						<td width=30>
							<p><a href="http://190.210.182.194/web/public/archivos/modcontable.rar"><img src="http://190.210.182.194/web/public/archivos/downloadfile.png" name="gr&aacute;ficos6" align=bottom width=27 height=21 border=0></a></p>
						</td>
						<td width=81>
							<p><a href="http://190.210.182.194/web/public/archivos/modcontable.rar">mod-contable</a></p>
						</td>
						<td width=100>
							<p>all win</p>
						</td>
						<td width=177>
							<p>Actualizacion modulo contable.</p>
						</td>
						<td width=100>
							<p>2.2.9</td>
						<td width=100>
							<p align=center>457 kb</p>
						</td>
					</tr>
				</table>
			</li>
		</ul>

	</div>
</div>