<div data-role="content" class="ui-grid-b">
	<div id="block-a">
		<ul data-role="listview" data-inset="true">
			<li data-role="list-divider">Opciones</li>
			<li data-icon="add"><a href="<?=$this->baseUrl();?>/logistica/pedidos/alta">Nuevo Pedido</a></li>
		</ul>
	</div>

	<div id="block-b" class="ui-block-b" data-theme="c">
		<ul data-role="listview" data-inset="true">
			<li data-role="list-divider">Pedidos(<?=$this->total;?> en total)</li>
			<li>
				<?php if(!empty($this->pedidos)): ?>
					<table>
						<thead>
							<tr class="ui-bar-b" align="center">
								<th width="40"></th>
								<th>Fecha de Alta</th>
								<th>Ultima Actualizaci&oacute;n</th>
								<th>Estado</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach($this->pedidos as $i => $v){ ?>
								<tr class="ui-btn-up-c">
									<td align="center"><a data-icon="gear" data-role="button" data-mini="true" data-iconpos="notext" data-legend="Acceder" class="button tiny" data-icon="icon-gear" href="<?=$this->baseUrl();?>/logistica/pedidos/ver/ped_id/<?=$v['ped_id'];?>"></a></td>
									<td><?=$v['fh'];?></td>
									<td><?=$v['fhult'];?></td>
									<td><?=$this->cache_ped_status[$v['ped_status']];?></td>
								</tr>
								<?php } ?>
						</tbody>
						<?php if($this->paginas > 1): ?>
							<tfoot>
								<tr>
									<td colspan="6" align="right"><?=$this->paginador($this->paginas);?></td>
								</tr>
							</tfoot>
							<?php endif; ?>
					</table>

					<?php else: ?>
					<p>No hay Pedidos en el sistema.</p>
					<?php endif; ?>

			</li>
		</ul>
	</div>
</div>