<div data-role="content" class="ui-grid-b">
	<div id="block-a">
		<ul data-role="listview" data-inset="true" data-theme="e">
			<li data-theme="a" data-icon="back"><a data-inline="true" data-mini="true" href="<?=$this->baseUrl();?>/informes/rentabilidad/index/suc_id/<?=$this->suc_id;?>/desde/<?=$this->desdeUrl;?>/hasta/<?=$this->hastaUrl;?>">Volver</a></li>
			<li>
				<b>Sucursal:</b> <?=$this->cache_sucursales[$this->suc_id];?><br />
			</li>
			<li><?=sizeof($this->equipos);?> remitos</li>
		</ul>
		<?php if(sizeof($this->equipos) > 0): ?>
			<center>
				<a data-theme="e" data-role="button" data-inline="true" data-mini="true" data-icon="gear" href="javascript:;" class="imprimir">Imprimir</a> <a data-theme="e" data-role="button" data-mini="true" data-inline="true" data-icon="gear" href="javascript:;" class="exportar">Exportar</a>
			</center>
			<?php endif; ?>

	</div>

	<?php if(!is_null($this->equipos)): ?>
		<div id="block-b" class="ui-block-b" data-theme="c">
			<ul data-role="listview" data-inset="true">
				<li data-role="list-divider">Equipos Ingresados - <b>Sucursal:</b> <?=$this->cache_sucursales[$this->suc_id];?> - Per&iacute;odo: <b><?=$this->periodo;?></b></li>
				<li>
					<table style="float: left;" style="margin-right:25px;">
						<thead>
							<tr align="center" class="ui-bar-b">
								<th>Nro Remito</th>
								<th>Fecha Carga</th>
								<th>Cant. Equipos</th>
								<th>Monto</th>
								<th>Monto Real</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach($this->equipos as $i => $v): ?>
								<tr class="ui-btn-up-c">
									<td align="right"><?=$v['nroremito'];?></td>
									<td><?=$v['fh_carga'];?></td>
									<td align="right"><?=$v['cantidad'];?> <?php $total1 += $v['cantidad'];?></td>
									<td align="right"><?=$this->currency->toCurrency($v['monto']);?> <?php $total += $v['monto'];?></td>
									<td align="right"><?=$this->currency->toCurrency($v['monto_r']);?> <?php $total2 += $v['monto_r'];?></td>
								</tr>
								<?php endforeach; ?>
						</tbody>
					</table>
					<table class="big" style="float: left;">
						<tr align="center" class="ui-bar-b">
							<th colspan="3">Totales</th>
						</tr>
						<tr align="center" class="ui-bar-b">
							<th>Cant. Equipos</th>
							<th>Monto</th>
							<th>Monto Real</th>
						</tr>
						<tr class="ui-btn-up-c">
							<td align="right"><?=$total1;?></td>
							<td align="right"><?=$this->currency->toCurrency($total);?></td>
							<td align="right"><?=$this->currency->toCurrency($total2);?></td>
						</tr>
					</table>
					<div class="clear"></div>
				</li>
			</ul>
		</div>
		<?php endif; ?>
</div>
