<?=$this->doctype().PHP_EOL;?>
<html xmlns="http://www.w3.org/1999/xhtml">
<html>
	<head>
<?=$this->headTitle();?>
<meta charset="<?=$this->getEncoding();?>" />
<?=$this->headLink()->prependStylesheet($this->baseUrl().'/public/css/reset.css').PHP_EOL;?>
<?=$this->headScript()->prependFile($this->baseUrl().'/public/js/jquery-1.7.1.min.js').PHP_EOL;?>
<style type="text/css">
nav ul, li { list-style:none; }
</style>

<style type="text/css">
	legend { font-size:14px; font-weight: bold;}
	table { border-collapse:collapse;}
	table th, table td { border:1px solid #ccc; padding:3px 4px; }
	table th { background:lightyellow;}
</style>
</head>
<body onload="window.print();">
	<div style="padding:10px;width:750px;margin:0 auto;">
	<?=$this->body;?>
	</div>

<script type="text/javascript">
$('.button').remove();
$('form').live('submit',function(){
return false;
});

</script>

</body>
</html>