<div data-role="content" class="ui-grid-b">
	<div id="block-a">
		<form method="post" action="<?=$this->baseUrl();?>/caja/index/diaria">
			<ul data-role="listview" data-inset="true" data-theme="e">
				<li data-role="list-divider">Informe de Caja Diaria</li>
				<li data-role="fieldcontain">Desde: <input type="text" name="desde" id="from" data-mini="true" value="<?=$this->desde;?>" size="8" /></li>
				<li data-role="fieldcontain">Hasta:	<input type="text" name="hasta" id="to" data-mini="true" value="<?=$this->hasta;?>" size="8" /></li>
				<li><?=$this->form->suc_id->renderViewHelper();?></li>
				<li id="pun_id"></li>
				<li><button data-theme="a" data-inline="true" data-mini="true" data-icon="search" title="Buscar" type="submit">Buscar</button></li>
			</ul>
		</form>
		<?php if(!empty($this->resultados)): ?>
			<center>
				<a data-theme="e" data-role="button" data-inline="true" data-mini="true" data-icon="gear" href="javascript:;" class="imprimir">Imprimir</a> <a data-theme="e" data-role="button" data-mini="true" data-inline="true" data-icon="gear" href="javascript:;" class="exportar">Exportar</a>
			</center>
			<?php endif; ?>
	</div>

	<?php if(!is_null($this->resultados)): ?>
		<div id="block-b" class="ui-block-b" data-theme="c">
			<ul data-role="listview" data-inset="true">
				<li data-role="list-divider"><b>Informe de Caja Diaria - <?=$this->cache_sucursales[$this->suc_id];?> - <?=$this->periodo;?></b></li>
				<li><?php if(!empty($this->resultados)): ?>
						<table>
							<thead>
								<tr class="ui-bar-b" align="center">
									<th>Punto</th>
									<th>Recargas</th>
									<th>Wanda</th>
									<th>Importe Efectivo</th>
									<th>Importe Tarjeta</th>
									<th>Total</th>
								</tr>
							</thead>
							<tbody>
								<?php foreach($this->resultados as $i => $v): ?>
									<tr class="ui-btn-up-c">
										<td><?=$this->cache_puntos[$v['IdPunto']];?></td>

										<td align="right"></td>
										<td align="right"><?=$this->currency->toCurrency($this->wanda[$v['IdPunto']]);?></td><?php $total4 += $this->wanda[$v['IdPunto']];?>
										<td align="right"><?=$this->currency->toCurrency($v['caj_Importe_caja_e']);?></td><?php $total5 += $v['caj_Importe_caja_e'];?>
										<td align="right"><?=$this->currency->toCurrency($v['caj_Importe_caja_t']);?></td><?php $total6 += $v['caj_Importe_caja_t'];?>
										<td align="right"><?=$this->currency->toCurrency($v['caj_Importe_caja_e']+$v['caj_Importe_caja_t']);?></td><?php $total7 += $v['caj_Importe_caja_e']+$v['caj_Importe_caja_t']+$this->wanda[$v['IdPunto']];?>
									</tr>
									<?php endforeach; ?>
							</tbody>
							<tfoot>
							<tr class="ui-bar-d" style="font-weight:bold">
								<td colspan="2" align="right">Totales</td>
								<td align="right"><?=$this->currency->toCurrency($total4);?></td>
								<td align="right"><?=$this->currency->toCurrency($total5);?></td>
								<td align="right"><?=$this->currency->toCurrency($total6);?></td>
								<td align="right"><?=$this->currency->toCurrency($total7);?></td>
							</tr>
						</tfoot>
						</table>
						<?php else: ?>
						<p>No hay resultados relacionados.</p>
						<?php endif; ?>
				</li>
			</ul>
		</div>
		<?php endif; ?>
</div>

<script type="text/javascript">
	$.get('<?=$this->baseUrl();?>/json/puntos-venta',function(d){
		$puntos = d;
		$('#suc_id').bind('change',function(){
			var s = '';
			$($puntos[+$(this).val()]).each(function(i,v){
				s += '<label style="font-size:11px"><input data-role="none" type="checkbox" name="pun_id[]" value="'+v.idpunto+'" />'+v.nombre+'</label><br />';
			});
			$('#pun_id').html(s);
<?php if(!empty($this->pun_id)): ?>
			$([<?=implode(',',$this->pun_id);?>]).each(function(){
				//alert(this);
				$('input[name="pun_id[]"][value="'+this+'"]').attr('checked',true);
			});
<?php endif; ?>
		}).show().change();
	},'json');
</script>