<div data-role="content" class="ui-grid-b">
	<div id="block-a">
		<form method="post" action="<?=$this->baseUrl();?>/caja/index/informe">
			<ul data-role="listview" data-inset="true" data-theme="e">
				<li data-role="list-divider">Informe de Caja</li>
				<li><?=$this->form->suc_id->renderViewHelper();?></li>
				<li><?=$this->form->pun_id->renderViewHelper();?></li>
				<li data-role="fieldcontain">Desde: <input class="icon-calendar" type="text" name="desde" id="from" data-mini="true" value="<?=$this->desde;?>" size="8" /></li>
				<li data-role="fieldcontain">Hasta:	<input type="text" id="to" name="hasta" value="<?=$this->hasta;?>" size="8" /></li>
				<li><button data-theme="a" data-inline="true" data-mini="true" data-icon="search" title="Buscar" type="submit">Buscar</button></li>
			</ul>
		</form>
<?php if(!empty($this->resultados)): ?>
			<center>
				<a data-theme="e" data-role="button" data-inline="true" data-mini="true" data-icon="gear" href="javascript:;" class="imprimir">Imprimir</a> <a data-theme="e" data-role="button" data-mini="true" data-inline="true" data-icon="gear" href="javascript:;" class="exportar">Exportar</a>
			</center>
<?php endif; ?>
	</div>


<?php if(!is_null($this->resultados)): ?>
	<div id="block-b" class="ui-block-b" data-theme="c">
		<ul data-role="listview" data-inset="true">
			<li data-role="list-divider"><b>Informe de Caja <?=$this->periodo;?></b></li>
			<li><?php if(!empty($this->resultados)): ?>
					<table>
						<thead>
							<tr class="ui-bar-b" align="center">
								<th rowspan="2">Fecha</th>
								<th colspan="4">Stock</th>
								<th rowspan="2">Importe Efectivo</th>
								<th rowspan="2">Importe Tarjeta</th>
								<th rowspan="2">Total</th>
							</tr>
							<tr class="ui-bar-b" align="center">
								<th>Equipos</th>
								<th>Imp. Eq</th>
								<th>Accesorios</th>
								<th>Imp. Acce</th>
							</tr>
						</thead>
						<tbody>
							<?php foreach($this->resultados as $i => $v): ?>
								<tr class="ui-btn-up-c">
									<td><?=$v['fecha'];?></td>
									<td align="right"><?=$v['caj_equipos'];?></td><?php $total1 += $v['caj_equipos'];?>
									<td align="right"><?=$this->currency->toCurrency($v['caj_Importe_equipos']);?></td><?php $total2 += $v['caj_Importe_equipos'];?>
									<td align="right"><?=$v['caj_accesorios'];?></td><?php $total3 += $v['caj_accesorios'];?>
									<td align="right"><?=$this->currency->toCurrency($v['caj_Importe_acce']);?></td><?php $total4 += $v['caj_Importe_acce'];?>
									<td align="right"><?=$this->currency->toCurrency($v['caj_Importe_caja_e']);?></td><?php $total5 += $v['caj_Importe_caja_e'];?>
									<td align="right"><?=$this->currency->toCurrency($v['caj_Importe_caja_t']);?></td><?php $total6 += $v['caj_Importe_caja_t'];?>
									<td align="right"><?=$this->currency->toCurrency($v['caj_Importe_caja_e']+$v['caj_Importe_caja_t']);?></td><?php $total7 += $v['caj_Importe_caja_e']+$v['caj_Importe_caja_t'];?>
								</tr>
								<?php endforeach; ?>
						</tbody>
						<tfoot>
							<tr class="ui-bar-d" style="font-weight:bold">
								<td>Totales</td>
								<td align="right"><?=$total1;?></td>
								<td align="right"><?=$this->currency->toCurrency($total2);?></td>
								<td align="right"><?=$total3;?></td>
								<td align="right"><?=$this->currency->toCurrency($total4);?></td>
								<td align="right"><?=$this->currency->toCurrency($total5);?></td>
								<td align="right"><?=$this->currency->toCurrency($total6);?></td>
								<td align="right"><?=$this->currency->toCurrency($total7);?></td>
							</tr>
						</tfoot>
					</table>
					<?php else: ?>
					<p>No hay resultados relacionados.</p>
					<?php endif; ?>
			</li>
		</ul>
	</div>
	<?php endif; ?>

</div>

<script type="text/javascript">
	$.get('<?=$this->baseUrl();?>/json/puntos-venta',function(d){
		$puntos = d;
		$('#suc_id').bind('change',function(){
			var s = '<option value="">[Puntos de Venta]</option>';
			$($puntos[+$(this).val()]).each(function(i,v){
				s += '<option value="'+v.idpunto+'">'+v.nombre+'</option>';
			});
			$('#pun_id').html(s).val('<?=$this->pun_id;?>').change();
		}).show().change();
	},'json');
</script>